### ISSUE TITLE
Unable to attach to vert.x instance

### ISSUE THREAD

**Issue by p14n** [djpowell/liverepl#5]
Hi, 

I can't attach to a running vert.x instance, I wondered if you could suggest anything here.

I can attach fine to a lein repl, but when attaching to vertx, I get the following exception thrown (in vert.x):

aused by: java.io.FileNotFoundException: Could not locate net/djpowell/liverepl/server/repl__init.class or net/djpowell/liverepl/server/repl.clj on classpath:

Adding the server jar fails with:

NoClassDefFoundError: clojure/lang/Associative

Cheers,
Dean

**Comment by djpowell** [comment]
I don't know much about vertx.

Are you using version 1.0?
Did you copy clojure.jar into the directory?  liverepl uses clojure from
the target's classpath normally, but if the target doesn't have clojure on
the classpath, it uses its local copy - so it could be that?

**Comment by p14n** [comment]
Thanks. 

Vert.x has its own classloader management.  There are two classloaders available, one of which I can connect to, but it doesn't have access to any of the namespaces I'm running.

I'll report back if I find anything.

Cheers,
Dean
